'use client';

import { useRef } from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { motion, useScroll, useTransform } from 'framer-motion';
import { ArrowRight, Sparkles, Heart, Share2, Palette, Wand2, Gift } from 'lucide-react';

import { AuroraBackground } from '@/components/backgrounds/AuroraBackground';
import { FloatingOrbs } from '@/components/backgrounds/FloatingOrbs';
import { SplitText } from '@/components/motion/SplitText';
import { Reveal } from '@/components/motion/Reveal';
import { MagneticButton } from '@/components/motion/MagneticButton';
import { GlassCard } from '@/components/motion/GlassCard';
import { RippleButton } from '@/components/motion/RippleButton';
import { useReducedMotion } from '@/hooks/useReducedMotion';

// Lazy-load the 3D particle field
const ParticleField = dynamic(
  () =>
    import('@/components/backgrounds/ParticleField').then((m) => ({
      default: m.ParticleField,
    })),
  { ssr: false }
);

export default function LandingPage() {
  const prefersReduced = useReducedMotion();
  const heroRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: heroRef,
    offset: ['start start', 'end start'],
  });

  // Parallax transforms
  const heroY = useTransform(scrollYProgress, [0, 1], [0, 150]);
  const heroOpacity = useTransform(scrollYProgress, [0, 0.8], [1, 0]);
  const heroScale = useTransform(scrollYProgress, [0, 1], [1, 0.9]);

  return (
    <main className="relative">
      {/* ─── Background Layers ─────────────────────────────────────────── */}
      <AuroraBackground />
      <FloatingOrbs />
      <ParticleField />

      {/* ─── Hero Section ──────────────────────────────────────────────── */}
      <section
        ref={heroRef}
        className="relative flex min-h-screen flex-col items-center justify-center overflow-hidden px-6"
        id="hero"
      >
        <motion.div
          className="relative z-10 flex max-w-5xl flex-col items-center text-center"
          style={
            prefersReduced
              ? undefined
              : { y: heroY, opacity: heroOpacity, scale: heroScale }
          }
        >
          {/* Pill badge */}
          <Reveal delay={0.2} direction="none" scale={0.9} blur={10}>
            <div className="glass mb-8 inline-flex items-center gap-2 rounded-full px-5 py-2 text-sm text-fg-secondary">
              <Sparkles className="h-4 w-4 text-accent-purple" />
              <span>AI-Powered Greeting Experiences</span>
            </div>
          </Reveal>

          {/* Main headline */}
          <h1 className="mb-6 text-5xl font-bold leading-[1.1] tracking-tight sm:text-6xl md:text-7xl lg:text-8xl"
              style={{ fontFamily: 'var(--font-display)' }}
          >
            <SplitText
              mode="words"
              delay={0.4}
              duration={0.8}
              gradient
            >
              Emotion Designed
            </SplitText>
            <SplitText
              mode="words"
              delay={0.9}
              duration={0.8}
              className="mt-2 block"
            >
              Beautifully.
            </SplitText>
          </h1>

          {/* Subtitle */}
          <Reveal delay={1.3} blur={6}>
            <p className="mb-10 max-w-2xl text-lg text-fg-secondary sm:text-xl md:text-2xl leading-relaxed">
              Turn your{' '}
              <span className="text-foreground font-medium">
                memories, feelings, and stories
              </span>{' '}
              into a cinematic, personalized greeting website — generated by AI,
              felt by heart.
            </p>
          </Reveal>

          {/* CTA Buttons */}
          <Reveal delay={1.6}>
            <div className="flex flex-col items-center gap-4 sm:flex-row">
              <MagneticButton
                className="animated-border rounded-[var(--radius-xl)] bg-bg-secondary px-8 py-4"
              >
                <Link
                  href="/create?new=1"
                  className="flex items-center gap-3 text-lg font-semibold text-foreground no-underline"
                >
                  <Wand2 className="h-5 w-5 text-accent-purple" />
                  Create Your Greeting
                  <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" />
                </Link>
              </MagneticButton>

              <RippleButton variant="ghost" size="lg">
                <Link
                  href="#how-it-works"
                  className="flex items-center gap-2 text-fg-secondary no-underline"
                >
                  See How It Works
                </Link>
              </RippleButton>
            </div>
          </Reveal>

          {/* Scroll indicator */}
          <Reveal delay={2.2} className="mt-16">
            <motion.div
              className="flex flex-col items-center gap-2 text-fg-muted"
              animate={prefersReduced ? undefined : { y: [0, 8, 0] }}
              transition={{
                duration: 2,
                repeat: Infinity,
                ease: 'easeInOut',
              }}
            >
              <span className="text-xs uppercase tracking-widest">
                Scroll to explore
              </span>
              <div className="h-8 w-[1px] bg-gradient-to-b from-fg-muted to-transparent" />
            </motion.div>
          </Reveal>
        </motion.div>

        {/* Mouse spotlight glow — follows cursor subtly */}
        <SpotlightGlow />
      </section>

      {/* ─── How It Works ──────────────────────────────────────────────── */}
      <section
        className="relative z-10 mx-auto max-w-6xl px-6 py-[var(--section-padding)]"
        id="how-it-works"
      >
        <Reveal>
          <div className="mb-16 text-center">
            <h2
              className="mb-4 text-3xl font-bold sm:text-4xl md:text-5xl"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              Three Steps to{' '}
              <span className="text-gradient">Something Unforgettable</span>
            </h2>
            <p className="mx-auto max-w-xl text-fg-secondary text-lg">
              No templates. No clip art. Just your story, beautifully told.
            </p>
          </div>
        </Reveal>

        <div className="grid gap-6 md:grid-cols-3 md:gap-8">
          {steps.map((step, i) => (
            <Reveal key={step.title} delay={i * 0.15} direction="up" className="h-full">
              <GlassCard
                animatedBorder={i === 1}
                padding="lg"
                className="h-full"
              >
                <div className="mb-6 flex items-center gap-4">
                  <div
                    className="flex h-12 w-12 items-center justify-center rounded-[var(--radius-md)]"
                    style={{
                      background: `linear-gradient(135deg, ${step.gradientFrom}, ${step.gradientTo})`,
                    }}
                  >
                    <step.icon className="h-6 w-6 text-white" />
                  </div>
                  <span className="text-sm font-medium text-fg-muted">
                    Step {i + 1}
                  </span>
                </div>

                <h3
                  className="mb-3 text-xl font-semibold text-foreground"
                  style={{ fontFamily: 'var(--font-display)' }}
                >
                  {step.title}
                </h3>
                <p className="text-fg-secondary leading-relaxed">
                  {step.description}
                </p>
              </GlassCard>
            </Reveal>
          ))}
        </div>
      </section>

      {/* ─── Feature Showcase ──────────────────────────────────────────── */}
      <section className="relative z-10 mx-auto max-w-6xl px-6 py-[var(--section-padding)]">
        <Reveal>
          <div className="mb-16 text-center">
            <h2
              className="mb-4 text-3xl font-bold sm:text-4xl md:text-5xl"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              Every Detail,{' '}
              <span className="text-gradient-warm">Crafted with Care</span>
            </h2>
            <p className="mx-auto max-w-xl text-fg-secondary text-lg">
              Each greeting is a living website with cinematic animations,
              personal photos, music, and your own words.
            </p>
          </div>
        </Reveal>

        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature, i) => (
            <Reveal key={feature.title} delay={i * 0.1} className="h-full">
              <GlassCard padding="md" className="h-full group">
                <feature.icon className="mb-4 h-8 w-8 text-accent-purple transition-colors group-hover:text-accent-purple-light" />
                <h3 className="mb-2 text-lg font-semibold text-foreground">
                  {feature.title}
                </h3>
                <p className="text-sm text-fg-secondary leading-relaxed">
                  {feature.description}
                </p>
              </GlassCard>
            </Reveal>
          ))}
        </div>
      </section>

      {/* ─── CTA Section ───────────────────────────────────────────────── */}
      <section className="relative z-10 mx-auto max-w-4xl px-6 py-[var(--section-padding)] mt-12 mb-20">
        <Reveal scale={0.95} blur={8} className="h-full">
          <div className="animated-border rounded-[var(--radius-xl)] bg-bg-secondary p-10 text-center md:p-16">
            <Gift className="mx-auto mb-6 h-12 w-12 text-accent-purple" />
            <h2
              className="mb-4 text-3xl font-bold sm:text-4xl md:text-5xl"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              Ready to Create{' '}
              <span className="text-gradient">Something Special</span>?
            </h2>
            <p className="mx-auto mb-8 max-w-lg text-lg text-fg-secondary">
              It takes just a few minutes to tell your story. The AI does the
              rest — crafting a one-of-a-kind experience they&apos;ll never
              forget.
            </p>
            <MagneticButton className="rounded-[var(--radius-xl)] bg-gradient-to-r from-accent-purple to-accent-blue px-10 py-5 shadow-lg shadow-accent-purple/25">
              <Link
                href="/create?new=1"
                className="flex items-center gap-3 text-lg font-semibold text-white no-underline"
              >
                Start Creating Now
                <ArrowRight className="h-5 w-5" />
              </Link>
            </MagneticButton>
          </div>
        </Reveal>
      </section>

      {/* ─── Footer ────────────────────────────────────────────────────── */}
      <footer className="relative z-10 py-12 text-center">
        <Reveal>
          <p className="text-sm text-fg-muted opacity-60">
            Made with <span className="text-accent-rose">❤</span> by GS
          </p>
        </Reveal>
      </footer>
    </main>
  );
}

// ─── Spotlight Glow Component ─────────────────────────────────────────────────

function SpotlightGlow() {
  const prefersReduced = useReducedMotion();

  if (prefersReduced) return null;

  return (
    <div
      className="pointer-events-none absolute inset-0 z-0 transition-opacity"
      aria-hidden="true"
      onMouseMove={(e) => {
        const target = e.currentTarget as HTMLElement;
        target.style.background = `radial-gradient(600px circle at ${e.clientX}px ${e.clientY}px, rgba(168, 85, 247, 0.04), transparent 60%)`;
      }}
    />
  );
}

// ─── Data ─────────────────────────────────────────────────────────────────────

const steps = [
  {
    icon: Heart,
    title: 'Tell Your Story',
    description:
      'Answer a few guided questions about who they are, your favorite memories, and what makes them special. Upload photos, voice notes, and music.',
    gradientFrom: 'var(--accent-purple)',
    gradientTo: 'var(--accent-blue)',
  },
  {
    icon: Sparkles,
    title: 'AI Creates Magic',
    description:
      'Our AI reads your answers, understands the emotion, and crafts a personalized website — from headlines to color palette to the storytelling flow.',
    gradientFrom: 'var(--accent-blue)',
    gradientTo: '#06b6d4',
  },
  {
    icon: Share2,
    title: 'Share the Love',
    description:
      'Get a unique link, QR code, or shareable card. Send it via text, WhatsApp, email — watch their reaction when they open it.',
    gradientFrom: 'var(--accent-rose)',
    gradientTo: 'var(--accent-purple)',
  },
];

const features = [
  {
    icon: Wand2,
    title: 'AI-Written Narrative',
    description:
      'The AI writes a beautiful story about them based on your memories and feelings.',
  },
  {
    icon: Palette,
    title: 'Cinematic Design',
    description:
      'Every greeting features smooth animations, 3D effects, and premium typography.',
  },
  {
    icon: Heart,
    title: 'Personal Photos & Music',
    description:
      'Upload photos, voice messages, and background music to make it truly theirs.',
  },
  {
    icon: Sparkles,
    title: 'Interactive Timeline',
    description:
      'Scroll through milestones and memories in a cinematic timeline experience.',
  },
  {
    icon: Share2,
    title: 'Easy Sharing',
    description:
      'Share via unique URL, QR code, or native share sheet — beautiful social previews included.',
  },
  {
    icon: Gift,
    title: 'Any Occasion',
    description:
      'Birthdays, anniversaries, graduations, weddings, farewells, or just because.',
  },
];
