import type { FormData } from '@/features/form/schema';

export const FORM_FIELD_KEYS = [
  'recipientName',
  'recipientNickname',
  'recipientAge',
  'recipientGender',
  'relationship',
  'occasionDate',
  'occasion',
  'customOccasion',
  'personalityDescription',
  'favoriteColor',
  'favoriteFood',
  'favoriteMovie',
  'favoriteSong',
  'favoriteHobby',
  'favoritePlace',
  'favoriteAnimal',
  'favoriteFlower',
  'travelDestination',
  'favoriteGame',
  'favoriteQuote',
  'whatMakesThemSpecial',
  'personalLetter',
  'funniestMemory',
  'bestMoment',
  'achievement',
  'dreamGoal',
  'timeline',
  'photos',
  'video',
  'voiceMessage',
  'backgroundMusic',
  'tone',
  'density',
  'themeMode',
  'language',
  'emojiUsage',
  'photoLayout',
  'senderName',
  'deviceTarget',
  'socialLinks',
  'additionalNotes',
  'mediaConsent',
] as const satisfies readonly (keyof FormData)[];

export const FIELD_LABELS: Record<(typeof FORM_FIELD_KEYS)[number], string> = {
  recipientName: 'Name',
  recipientNickname: 'Nickname',
  recipientAge: 'Age',
  recipientGender: 'Pronouns',
  relationship: 'Relationship',
  occasionDate: 'Occasion date',
  occasion: 'Occasion',
  customOccasion: 'Custom occasion',
  personalityDescription: 'Personality',
  favoriteColor: 'Favorite color',
  favoriteFood: 'Favorite food',
  favoriteMovie: 'Favorite movie',
  favoriteSong: 'Favorite song',
  favoriteHobby: 'Favorite hobby',
  favoritePlace: 'Favorite place',
  favoriteAnimal: 'Favorite pet',
  favoriteFlower: 'Favorite flower',
  travelDestination: 'Dream destination',
  favoriteGame: 'Favorite game',
  favoriteQuote: 'Favorite quote',
  whatMakesThemSpecial: 'What makes them special',
  personalLetter: 'Your note',
  funniestMemory: 'Funniest memory',
  bestMoment: 'Best moment',
  achievement: 'Achievement',
  dreamGoal: 'Dream goal',
  timeline: 'Timeline',
  photos: 'Photos',
  video: 'Video',
  voiceMessage: 'Voice message',
  backgroundMusic: 'Music',
  tone: 'Tone',
  density: 'Detail level',
  themeMode: 'Theme mode',
  language: 'Language',
  emojiUsage: 'Emoji style',
  photoLayout: 'Photo layout',
  senderName: 'Presented by',
  deviceTarget: 'Viewing device',
  socialLinks: 'Social links',
  additionalNotes: 'Extra notes',
  mediaConsent: 'Media consent',
};

const FIELD_OUTPUT_HOME: Record<(typeof FORM_FIELD_KEYS)[number], string> = {
  recipientName: 'recipientName, heroHeadline, ogTitle',
  recipientNickname: 'heroHeadline or letter',
  recipientAge: 'story or memoryHighlights',
  recipientGender: 'relationship-appropriate voice',
  relationship: 'theme.archetype, greetingMessage, letter',
  occasionDate: 'timeline or story',
  occasion: 'theme.themeLabel, greetingMessage',
  customOccasion: 'theme.themeLabel or closingMessage',
  personalityDescription: 'story',
  favoriteColor: 'theme.accent and visual mood',
  favoriteFood: 'signatureLine, memoryHighlights, motifs',
  favoriteMovie: 'memoryHighlights or playfulAside',
  favoriteSong: 'story or playfulAside',
  favoriteHobby: 'memoryHighlights, motifs',
  favoritePlace: 'story, timeline, motifs',
  favoriteAnimal: 'signatureLine, playfulAside, motifs',
  favoriteFlower: 'motifs or story',
  travelDestination: 'story or closingMessage',
  favoriteGame: 'playfulAside or memoryHighlights',
  favoriteQuote: 'quotes or letter',
  whatMakesThemSpecial: 'story',
  personalLetter: 'letter',
  funniestMemory: 'story or memoryHighlights',
  bestMoment: 'story or timeline',
  achievement: 'story or memoryHighlights',
  dreamGoal: 'story or closingMessage',
  timeline: 'timeline',
  photos: 'gallery',
  video: 'gallery or memoryHighlights',
  voiceMessage: 'letter mood',
  backgroundMusic: 'music',
  tone: 'all visible copy voice',
  density: 'theme.density',
  themeMode: 'theme.mode',
  language: 'all visible copy language',
  emojiUsage: 'emoji restraint',
  photoLayout: 'gallery pacing',
  senderName: 'presentedBy and dedication',
  deviceTarget: 'copy length and layout pacing',
  socialLinks: 'closingMessage or dedication context',
  additionalNotes: 'story, letter, or playfulAside',
  mediaConsent: 'media handling',
};

export function buildCoverageMap(): Record<(typeof FORM_FIELD_KEYS)[number], string> {
  return FORM_FIELD_KEYS.reduce((coverage, key) => {
    coverage[key] = FIELD_OUTPUT_HOME[key];
    return coverage;
  }, {} as Record<(typeof FORM_FIELD_KEYS)[number], string>);
}
